# frozen_string_literal = true

# RBS type definitions for user.rb

class User
  attr_reader id: Integer
  attr_reader first_name: String
  attr_reader first_name: String
  attr_reader last_name: String
  attr_reader email: String
  attr_reader company_id: Integer
  attr_reader email_status: bool
  attr_reader active_status: bool
  attr_reader tokens: Integer

  def initialize: (Integer id, String first_name, String last_name, String email, Integer company_id, bool email_status, bool active_status, Integer tokens) -> void
end
